export const transactions = [
  {
    id: 1,
    icon: "Game",
    name: "GTR 5 ",
    category: "Gadget & Gear",
    amount: 160,
    date: "2023-05-17",
    revenue: true,
    expenses: false,
  },
  {
    id: 2,
    icon: "Game 2",
    name: "GTR 5 ",
    category: "Gadget & Gear",
    amount: 160,
    date: "2023-05-17",
    revenue: true,
    expenses: false,
  },
  {
    id: 3,
    icon: "Game 3",
    name: "GTR 5 ",
    category: "Gadget & Gear",
    amount: 160,
    date: "2023-05-17",
    revenue: false,
    expenses: true,
  },
  {
    id: 4,
    icon: "Game 3",
    name: "GTR 5",
    category: "Gadget & Gear",
    amount: 160,
    date: "2023-05-17",
    revenue: true,
    expenses: false,
  },
  {
    id: 5,
    icon: "Game 3",
    name: "GTR 5",
    category: "Gadget & Gear",
    amount: 160,
    date: "2023-05-17",
    revenue: false,
    expenses: true,
  },
];
